{% set name = "lale" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lale-{{ version }}.tar.gz
  sha256: b7b60cdfffe454522a21c0e569e9ea86574e3f602a7208f8f8b424af5bc727fa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - black >=22.1.0
    - python-graphviz
    - hyperopt >=0.2,<=0.2.5
    - jsonschema <=4.20.0
    - jsonsubschema >=0.0.6
    - scikit-learn >=1.0.0,<1.5.0
    - scipy
    - pandas
    - packaging
    - decorator
    - astunparse
    - typing-extensions

test:
  imports:
    - lale
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/IBM/lale
  summary: Library for Semi-Automated Data Science
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - josk0
